### ISSUE TITLE
installed include dir not updated

### ISSUE THREAD

**Issue by kazzmir** [kazzmir/r-tech1#1]
```
$ make install
...edit include/r-tech1/whatever.h...
$ make install
```

whatever.h will not be updated in the install directory.

A workaround is to rm -rf the install/include/r-tech1 directory and re-run make install.

**Comment by juvinious** [comment]
I noticed that was happening last night, too tired to fix it. I'll fix it
when I get home later today.
2015. 5. 8. 13:07에 "Jon Rafkind" notifications@github.com님이 작성:
