### ISSUE TITLE
rtech1 init test link failure

### ISSUE THREAD

**Issue by WilliamTambellini** [kazzmir/r-tech1#2]
run scons as usual from the rtech1 root forder:

Building` library lib/libr-tech1.a
Indexing library lib/libr-tech1.a
Linking build/release/tests/init/init-test
/usr/bin/ld: lib/libr-tech1.a(unzip.o): undefined reference to symbol 'inflateInit2_'
/usr/bin/ld: note: 'inflateInit2_' is defined in DSO /lib64/libz.so.1 so try adding it to the linker command line
/lib64/libz.so.1: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
scons: **\* [build/release/tests/init/init-test] Error 1
scons: building terminated because of errors.

Possible fix: add such line to tests/SConscript
`env.Append(LIBS=['z'])`

**Comment by kazzmir** [comment]
I'm not sure why you are getting that link error, for me it works. Anyway, I just pushed a commit that doesn't build the tests by default. You don't need them anyway. The only important part of the build is lib/r-tech1.a.
