### ISSUE TITLE
Error when running Make command - 'TypeError: argument of type 'Dir' is not iterable:"

### ISSUE THREAD

**Issue by mikeym88** [kazzmir/r-tech1#3]
I get the following error when trying to compile the code in Ubuntu 16.04:

    TypeError: argument of type 'Dir' is not iterable:
      File "/home/user/workspace/paintown-master/SConstruct", line 1475:
        env.Append(ARCHIVES = [buildRtech(rtech1Env)])
      File "/home/user/workspace/paintown-master/SConstruct", line 1470:
        return env.SConscript('r-tech1/SConscript', variant_dir = buildDir + '/r-tech1', exports = ['env', 'root'])
      File "/usr/lib/scons/SCons/Script/SConscript.py", line 551:
        return _SConscript(self.fs, *files, **subst_kw)
      File "/usr/lib/scons/SCons/Script/SConscript.py", line 260:
        exec _file_ in call_stack[-1].globals
      File "/home/user/workspace/paintown-master/build/allegro5/r-tech1/SConscript", line 91:
        pcflags = createList(env['CPPPATH'], 'I')
      File "/home/user/workspace/paintown-master/build/allegro5/r-tech1/SConscript", line 89:
        deps += '-{0}{1} '.format(modifier, item) if 'r-tech1' not in item else ''
    Get scons at www.scons.org or read the README for compilation instructions
    Makefile:9: recipe for target 'all' failed
    make: *** [all] Error 1

Anything I can do/change to resolve this?

**Comment by kazzmir** [comment]
Did you do a build in r-tech1, and then do a build in paintown? If you did a build in r-tech1 it will create a 'build' directory. Make sure you delete that directory, then just do a build from paintown.

For some reason scons gets confused when it sees r-tech1/build. I've spent a long time trying to resolve it, but the easiest fix thus far is just to delete r-tech1/build.

**Comment by mikeym88** [comment]
I tried deleting the build folder from within r-tech1, and it is still giving me that error.

So the r-tech1 folder (named `r-tech1` and not `r-tech1-master`, correct?) is supposed to be in the paintown directoy? And the contents of the paintown-data folder should go in the data folder?

    paintown
       |- r-tech1
       |- data
       |- ...
       
The error occurs after the following check:

    Checking if install prefix set ... (cached) defaulting to [/usr/local](cached) no

What kind of prefix is the python script looking for?

**Comment by kazzmir** [comment]
Right, the directory 'r-tech1' should be inside the directory folder. I get the same output as you, 'install prefix set to no' and my build is ok. You can also try 'scons verbose=1' and then look at config.log, or paste its contents here.

Here are the config output lines from scons during one of my successful builds:

```
Build type: Allegro5
Checking for Allegro 5 ... (cached) 5(cached) found version 5 [Non-monolithic]yes
Checking for freetype2 ... (cached) found(cached) yes
Checking if install prefix set ... (cached) defaulting to [/usr/local](cached) no
Checking for Allegro 5 ... (cached) 5(cached) found version 5 yes
Checking for threads... (cached)  pthreads(cached) yes
Checking for C header file ft2build.h... yes
Checking for C header file png.h... yes
Checking if we need rtti... yes
Checking for ogg and vorbis... no
Checking for libmpg123... no
Checking for libmad... no
Checking for threads... (cached)  pthreads(cached) yes
Checking if we need rtti... yes
Checking if python is embeddable... no
Checking if python is embeddable... no

```

**Comment by kazzmir** [comment]
Sorry all of that was on the wrong track. d6fffcc1ef fixes this. You also need to git update the paintown directory for a corresponding change.
